### ISSUE TITLE
Add generic events template

### ISSUE THREAD

**Issue by sangeetha5491** [adobe/aio-template-submission#743]
### Link to GitHub repo

https://github.com/adobe/generator-add-events-generic

### npm package name

@adobe/generator-add-events-generic

**Comment by lenaorobei** [comment]
Hey, @sangeetha5491!
I can see that the template was added to the registry https://github.com/adobe/aio-template-submission/commit/efff8610d76eddceedffd42253e8487ff8609c5e
You can verify it by running `aio app init`.
It looks like there is an issue with our automation so it did not close this ticket automatically.
cc @slitviachenko
